<?php

declare(strict_types=1);

namespace App\Domain\Payment;

use App\Domain\Money\Bps;
use App\Models\Subscription;
use App\Models\SubscriptionPayment;
use DateTimeImmutable;
use Illuminate\Support\Str;
use InvalidArgumentException;

/**
 * §5.1: the inbound side of the pipeline, first half.
 *
 * The payment row is written *before* the charge request goes out, carrying a
 * key we generated ourselves. That ordering is the whole point: without a row
 * to collide with, a request retried before any provider reference exists has
 * nothing to dedupe against — the inbound mirror of the `unknown` payout state
 * (§11).
 */
final class InitiatePaymentService
{
    /**
     * @param  array<int, int>  $instructorIds  the instructors the subscription grants access to (§5.2)
     */
    public function initiate(
        Subscription $subscription,
        int $amountMinor,
        int $platformRateBps,
        array $instructorIds,
        string $provider,
        DateTimeImmutable $termStart,
        DateTimeImmutable $termEnd,
        ?string $clientIdempotencyKey = null,
    ): SubscriptionPayment {
        // §5.2: "distinct instructors", determined at payment time. Normalised
        // here the same way EqualSplitAllocator normalises, so the frozen set is
        // canonical and the allocator has nothing left to decide.
        $ids = array_values(array_unique(array_map('intval', $instructorIds)));
        sort($ids);

        if ($ids === []) {
            // The CHECK on instructor_ids refuses this too. Both exist because
            // §14 keeps model-level validation and the constraint in step.
            throw new InvalidArgumentException('A payment must name at least one instructor to allocate to.');
        }

        // §9.1: a retried initiate reuses the same key and this insert simply
        // fails on UNIQUE(client_idempotency_key). That rejection is the guard;
        // it is deliberately not caught and turned into a silent success.
        return SubscriptionPayment::create([
            'subscription_id' => $subscription->id,
            'amount_minor' => $amountMinor,
            'currency' => $subscription->currency,
            'instructor_ids' => $ids,
            // §5.3: the rate is frozen here and never read live again. A later
            // change from 20% to 25% cannot rewrite this payment's history.
            'platform_rate_bps' => $platformRateBps,
            // §5.4: floor the pool, derive the cut. Computed through Bps so the
            // direction can never drift from §8's residual-claimant principle.
            'platform_cut_minor' => Bps::cut($amountMinor, $platformRateBps),
            'term_start' => $termStart,
            'term_end' => $termEnd,
            // §5.1: generated by us, before the call.
            'client_idempotency_key' => $clientIdempotencyKey ?? (string) Str::uuid(),
            'provider' => $provider,
            // §5.1: null until they confirm. Many NULLs are tolerated in the
            // (provider, provider_reference) index precisely so this can wait.
            'provider_reference' => null,
            'status' => 'pending',
            'paid_at' => null,
        ]);
    }
}
