<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Domain\Money\Bps;
use App\Models\Subscription;
use App\Models\SubscriptionPayment;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends Factory<SubscriptionPayment>
 */
class SubscriptionPaymentFactory extends Factory
{
    protected $model = SubscriptionPayment::class;

    public function definition(): array
    {
        $amount = 35_000;
        $bps = 2_000;

        return [
            'subscription_id' => Subscription::factory(),
            'amount_minor' => $amount,
            'currency' => 'EGP',
            // §5.3: the rate and the cut are snapshotted, never recomputed.
            'platform_rate_bps' => $bps,
            // §5.4: derived through Bps so a factory row can never contradict
            // the production rounding rule, nor violate the CHECK that the cut
            // does not exceed the gross.
            'platform_cut_minor' => Bps::cut($amount, $bps),
            'term_start' => now()->utc()->startOfDay()->subDays(30)->toImmutable(),
            'term_end' => now()->utc()->startOfDay()->addDays(60)->toImmutable(),
            // §5.1: generated by us, before the call.
            'client_idempotency_key' => (string) Str::uuid(),
            'provider' => 'scripted',
            // §5.1: null until the provider confirms. Many NULLs are tolerated
            // in the (provider, provider_reference) unique index.
            'provider_reference' => null,
            'status' => 'pending',
            'paid_at' => null,
        ];
    }

    public function confirmed(): static
    {
        return $this->state(fn (array $attributes) => [
            'provider_reference' => 'ref_'.Str::random(16),
            'status' => 'paid',
            'paid_at' => now()->utc()->toImmutable(),
        ]);
    }
}
