<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('subscription_payments', function (Blueprint $table) {
            $table->id();

            // restrictOnDelete, never cascade: a money row must not be removed
            // by a delete somewhere else in the graph.
            $table->foreignId('subscription_id')
                ->constrained('subscriptions')
                ->restrictOnDelete();

            $table->unsignedBigInteger('amount_minor');
            $table->char('currency', 3);

            // §5.3: the rate and the cut are frozen onto the payment, never
            // recomputed. A later change from 20% to 25% cannot rewrite history.
            // §3: basis points as a whole number — 20% is 2000, never 0.20.
            $table->unsignedSmallInteger('platform_rate_bps');
            $table->unsignedBigInteger('platform_cut_minor');

            $table->dateTime('term_start');
            $table->dateTime('term_end');

            // §5.1: generated by us, before the call. Guards a request retried
            // before any provider reference exists.
            $table->char('client_idempotency_key', 36);

            $table->string('provider', 64);

            // §5.1: generated by them, after the call. Nullable until confirmed,
            // and namespaced by provider because references are only unique
            // within a provider.
            $table->string('provider_reference', 191)->nullable();

            $table->string('status', 32);
            $table->dateTime('paid_at')->nullable();

            $table->timestamps();

            $table->unique('client_idempotency_key');

            // §5.1: many NULLs are *tolerated* here — uniqueness for unconfirmed
            // rows is carried by client_idempotency_key instead.
            $table->unique(['provider', 'provider_reference']);
        });

        DB::statement(
            'ALTER TABLE subscription_payments ADD CONSTRAINT chk_subscription_payments_amount_positive
             CHECK (amount_minor > 0)'
        );

        // §3: 10000 basis points is 100%. Bps::SCALE mirrors this in PHP.
        DB::statement(
            'ALTER TABLE subscription_payments ADD CONSTRAINT chk_subscription_payments_rate_bps
             CHECK (platform_rate_bps <= 10000)'
        );

        // §5.4: the pool is floored and the cut is the residue, so the cut can
        // never exceed the gross.
        DB::statement(
            'ALTER TABLE subscription_payments ADD CONSTRAINT chk_subscription_payments_cut_le_amount
             CHECK (platform_cut_minor <= amount_minor)'
        );
    }

    public function down(): void
    {
        Schema::dropIfExists('subscription_payments');
    }
};
